//! Read a harvested DCS unit range database and report on it.
//!
//! The snapshot comes from the engine (`bflib/src/unitdb.rs` walks `_G.db.Units`
//! in the hooks Lua state and writes `Logs/unitdb.json`; bfdb serves the same
//! thing from `/api/unitdb`). `data/unitdb-baseline.json` is the checked-in
//! fallback for when there's no server to ask.
//!
//! The point of the markdown output is that range tables — the wiki's in
//! particular — stop being hand-typed and start being generated from whatever
//! DCS actually says.

use anyhow::{bail, Context, Result};
use serde_derive::{Deserialize, Serialize};
use std::{collections::BTreeMap, path::PathBuf};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UnitInfo {
    #[serde(default)]
    pub typ: String,
    #[serde(default)]
    pub display_name: Option<String>,
    #[serde(default)]
    pub category: Option<String>,
    #[serde(default)]
    pub attributes: Vec<String>,
    #[serde(default)]
    pub threat_range_m: Option<f64>,
    #[serde(default)]
    pub threat_range_min_m: Option<f64>,
    #[serde(default)]
    pub detection_range_m: Option<f64>,
    #[serde(default)]
    pub max_target_detection_range_m: Option<f64>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UnitDb {
    #[serde(default)]
    pub dcs_version: Option<String>,
    #[serde(default)]
    pub harvested_at: Option<String>,
    #[serde(default)]
    pub by_type: BTreeMap<String, UnitInfo>,
}

#[derive(clap::Args, Clone, Debug, Serialize)]
pub struct UnitDbCmd {
    /// the harvested snapshot to read (Logs/unitdb.json, GET /api/unitdb, or
    /// the checked-in data/unitdb-baseline.json)
    #[clap(long, default_value = "data/unitdb-baseline.json")]
    snapshot: PathBuf,
    /// only units carrying this DCS attribute, e.g. "Indirect fire", "SAM SR",
    /// "Artillery". Repeatable; a unit must carry all of them.
    #[clap(long = "attribute")]
    attributes: Vec<String>,
    /// only units whose type name or display name contains this (case
    /// insensitive)
    #[clap(long)]
    grep: Option<String>,
    /// only units DCS gives an engagement range
    #[clap(long)]
    armed_only: bool,
    /// emit a markdown table instead of JSON
    #[clap(long)]
    markdown: bool,
    /// write to this file instead of stdout
    #[clap(long)]
    output: Option<PathBuf>,
}

fn km(v: Option<f64>) -> String {
    match v {
        // Gun minimums are tens of metres; rounding those to "0.0 km" reads as
        // "no minimum", which is the opposite of what it means.
        Some(v) if v < 1000.0 => format!("{v:.0} m"),
        Some(v) => format!("{:.1} km", v / 1000.0),
        None => "—".to_string(),
    }
}

pub fn run(cmd: &UnitDbCmd) -> Result<()> {
    let body = std::fs::read_to_string(&cmd.snapshot)
        .with_context(|| format!("reading snapshot {:?}", cmd.snapshot))?;
    let db: UnitDb = serde_json::from_str(&body)
        .with_context(|| format!("parsing snapshot {:?}", cmd.snapshot))?;
    let grep = cmd.grep.as_ref().map(|g| g.to_lowercase());
    let mut rows: Vec<&UnitInfo> = db
        .by_type
        .values()
        .filter(|u| {
            cmd.attributes
                .iter()
                .all(|want| u.attributes.iter().any(|a| a == want))
        })
        .filter(|u| !cmd.armed_only || u.threat_range_m.is_some())
        .filter(|u| match &grep {
            None => true,
            Some(g) => {
                u.typ.to_lowercase().contains(g)
                    || u.display_name
                        .as_deref()
                        .map(|d| d.to_lowercase().contains(g))
                        .unwrap_or(false)
            }
        })
        .collect();
    if rows.is_empty() {
        bail!("no units matched");
    }
    // Longest reach first: for a range table that is the interesting order.
    rows.sort_by(|a, b| {
        b.threat_range_m
            .unwrap_or(0.0)
            .partial_cmp(&a.threat_range_m.unwrap_or(0.0))
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.typ.cmp(&b.typ))
    });
    let out = if cmd.markdown {
        let mut s = String::new();
        if let Some(v) = &db.dcs_version {
            s.push_str(&format!("<!-- generated by `bftools unit-db` from DCS {v} -->\n\n"));
        }
        s.push_str("| Unit | Type | Min range | Max range | Detection |\n");
        s.push_str("| --- | --- | ---: | ---: | ---: |\n");
        for u in &rows {
            s.push_str(&format!(
                "| {} | `{}` | {} | {} | {} |\n",
                u.display_name.as_deref().unwrap_or(&u.typ),
                u.typ,
                km(u.threat_range_min_m),
                km(u.threat_range_m),
                km(u.detection_range_m.or(u.max_target_detection_range_m)),
            ));
        }
        s
    } else {
        serde_json::to_string_pretty(&rows)?
    };
    match &cmd.output {
        Some(p) => {
            std::fs::write(p, out).with_context(|| format!("writing {p:?}"))?;
            eprintln!("wrote {} rows to {:?}", rows.len(), p);
        }
        None => print!("{out}"),
    }
    Ok(())
}
