// ─────────────────────────────────────────────────────────────────────────────
// Campaign Configuration — DEFAULT VALUES
//
// Do NOT edit this file for deployment. Instead, create a campaign.json file
// and pass it to bfdb at startup:
//
//   bfdb.exe --db "E:\Saved Games\DCS\bfdb" --config "E:\campaign.json"
//
// The JSON file is served at GET /api/config and deep-merged over these
// defaults at runtime. Only include keys you want to override.
//
// See campaign.sample.json in the repo root for a ready-to-edit template.
// ─────────────────────────────────────────────────────────────────────────────

export interface EngineCredit {
  name:   string
  handle: string
  role:   string
}

export interface ServerCredit {
  name: string
  role: string
}

export interface CampaignConfig {
  // Identity
  name:      string
  shortName: string
  tagline:   string
  version:   string
  logoUrl:   string   // URL or path to logo image — leave empty to show text monogram
  // Links
  discord:     string
  server:      string
  serverIp:    string
  websiteUrl:  string
  donationUrl: string   // leave empty to hide the donation button
  // Faction labels
  blueLabel: string
  redLabel:  string
  // Colors
  accentColor:       string
  accentHoverColor:  string
  blueColor:         string
  redColor:          string
  bgColor:           string
  bgCardColor:       string
  bgElevatedColor:   string
  borderColor:       string
  // Map
  mapCenter: [number, number]
  mapZoom:   number
  // Dashboard layout
  dashboardRightPanelWidth:  number   // px width of the live panel on the right
  dashboardObjectivesHeight: number   // px max-height of the objectives strip
  dashboardKillFeedCount:    number   // number of recent kills to show
  // Credits
  engineCredits: EngineCredit[]
  serverCredits: ServerCredit[]
}

export const campaignDefaults: CampaignConfig = {
  name:      'Vector Strike',
  shortName: 'VS',
  tagline:   'Where every sortie shapes the war.',
  version:   'v3.0',
  logoUrl:   '',

  discord:     'https://discord.gg/XyGkb3WAXS',
  server:      'The Coop · Operation Vector Strike',
  serverIp:    '',
  websiteUrl:  '',
  donationUrl: '',

  blueLabel: 'BLUFOR',
  redLabel:  'REDFOR',

  accentColor:      '#4d7c0f',
  accentHoverColor: '#65a30d',
  blueColor:        '#3b82f6',
  redColor:         '#ef4444',
  bgColor:          '#0a0a0a',
  bgCardColor:      '#111111',
  bgElevatedColor:  '#191919',
  borderColor:      '#2a2a2a',

  mapCenter: [33.0, 36.5],
  mapZoom:   7,

  dashboardRightPanelWidth:  300,
  dashboardObjectivesHeight: 220,
  dashboardKillFeedCount:    30,

  engineCredits: [
    { name: 'EvilKipper', handle: '',               role: 'Creator'              },
    { name: 'KillerDog',  handle: 'No15 | KillerDog', role: 'Lead Developer'       },
    { name: 'EagleEye',   handle: '[.ID] EagleEye',   role: 'Tester & Contributor' },
  ],

  serverCredits: [],
}

// This is the live config object — populated at startup by main.tsx after
// fetching /api/config and merging over the defaults above.
// All components import `campaign` from this module.
export const campaign: CampaignConfig = { ...campaignDefaults }
