// ─────────────────────────────────────────────────────────────────────────────
// Campaign Configuration — DEFAULT VALUES
//
// Do NOT edit this file for deployment. Instead, create a campaign.json file
// and pass it to bfdb at startup:
//
//   bfdb.exe --db "E:\Saved Games\DCS\bfdb" --config "E:\campaign.json"
//
// The JSON file is served at GET /api/config and deep-merged over these
// defaults at runtime. Only include keys you want to override.
//
// See campaign.sample.json in the repo root for a ready-to-edit template.
// ─────────────────────────────────────────────────────────────────────────────

export interface EngineCredit {
  name:   string
  handle: string
  role:   string
}

export interface ServerCredit {
  name: string
  role: string
}

export interface CampaignConfig {
  // Identity
  name:      string
  shortName: string
  tagline:   string
  version:   string
  logoUrl:   string   // URL or path to logo image — leave empty to show text monogram
  // Links
  discord:     string
  server:      string
  serverIp:    string
  websiteUrl:  string
  donationUrl: string   // leave empty to hide the donation button
  // Faction labels
  blueLabel: string
  redLabel:  string
  // Colors — override the military palette if desired
  accentColor:       string   // primary OD-green accent
  accentHoverColor:  string   // brighter accent on hover
  blueColor:         string   // BLUFOR faction color
  redColor:          string   // REDFOR faction color
  bgColor:           string   // page background
  bgCardColor:       string   // card background
  bgElevatedColor:   string   // elevated / input background
  borderColor:       string   // border color
  // Map
  mapCenter: [number, number]   // [lat, lon]
  mapZoom:   number
  // Dashboard layout
  dashboardRightPanelWidth:  number   // px — right panel column width (unused in new layout)
  dashboardObjectivesHeight: number   // px — objectives strip max-height (unused in new layout)
  dashboardKillFeedCount:    number   // number of recent kills shown in the engagement log
  // Background / theme
  backgroundImage:        string   // URL to a background image — leave empty for none
  backgroundImageOpacity: number   // 0–1 opacity of the background image, default 0.08
  backgroundImageSize:    string   // CSS background-size value, default 'cover'
  backgroundImageBlend:   string   // CSS mix-blend-mode, default 'overlay'
  camoPattern:            string   // built-in pattern: 'none' | 'digital' | 'hex' | 'terrain' | 'multicam'
  camoOpacity:            number   // 0–1 opacity of the camo overlay, default 0.05
  // Integrations
  srsUrl: string   // SRS server URL e.g. "http://localhost:5002" — leave empty to hide SRS panel
  // Credits
  engineCredits: EngineCredit[]
  serverCredits: ServerCredit[]
}

export const campaignDefaults: CampaignConfig = {
  name:      'Vector Strike',
  shortName: 'VS',
  tagline:   'Where every sortie shapes the war.',
  version:   'v3.0',
  logoUrl:   '',

  discord:     'https://discord.gg/XyGkb3WAXS',
  server:      'The Coop · Operation Vector Strike',
  serverIp:    '',
  websiteUrl:  '',
  donationUrl: '',

  blueLabel: 'BLUFOR',
  redLabel:  'REDFOR',

  accentColor:      '#4d7c0f',
  accentHoverColor: '#65a30d',
  blueColor:        '#3b82f6',
  redColor:         '#ef4444',
  bgColor:          '#0a0a0a',
  bgCardColor:      '#111111',
  bgElevatedColor:  '#191919',
  borderColor:      '#2a2a2a',

  mapCenter: [33.0, 36.5],
  mapZoom:   7,

  dashboardRightPanelWidth:  300,
  dashboardObjectivesHeight: 220,
  dashboardKillFeedCount:    30,

  backgroundImage:        '',
  backgroundImageOpacity: 0.08,
  backgroundImageSize:    'cover',
  backgroundImageBlend:   'overlay',
  camoPattern:            'none',
  camoOpacity:            0.05,

  srsUrl: '',

  engineCredits: [
    { name: 'EvilKipper', handle: '',               role: 'Creator'              },
    { name: 'KillerDog',  handle: 'No15 | KillerDog', role: 'Lead Developer'       },
    { name: 'EagleEye',   handle: '[.ID] EagleEye',   role: 'Tester & Contributor' },
  ],

  serverCredits: [
    { name: 'Hacker', role: 'Server Host — Founder, 61st ATP' },
  ],
}

// This is the live config object — populated at startup by main.tsx after
// fetching /api/config and merging over the defaults above.
// All components import `campaign` from this module.
export const campaign: CampaignConfig = { ...campaignDefaults }
